import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Jumbotron from '../components/Jumbotron/Jumbotron'
import Nav from '../components/Nav/Nav'
import DefaultLayout from '../layout/DefaultLayout'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>First Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
        <Jumbotron />
      </DefaultLayout>
    </div>
  )
}

export default Home
